name: hello-world
'on': push
jobs:
  my-job:
    runs-on: self-hosted
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: step2
        run: source fleet-onprem-dscc-test/test.sh
        
